### ISSUE TITLE
Erro ao instalar no WebStorm 2019.2

### ISSUE THREAD

**Issue by Brunowilliang** [getomni/jetbrains#10]
Seguindo os dizeres de [INSTALL.md ](https://github.com/getomni/jetbrains/blob/main/INSTALL.md) tentei instalar e apareceu o seguinte erro. 
![ Uploading Captura de Tela 2021-03-25 às 14.46.23.png...]()
>OBS: Usei o arquivo disponível para download em INSTALL.md 
>Versão WebStorm 2019.2

**Comment by breno-felipe** [comment]
Hey, @Brunowilliang 

The incompatibility problem is being solved by @Mayconsgs

It will soon be resolved

**Comment by breno-felipe** [comment]
> Seguindo os dizeres de INSTALL.md tentei instalar e apareceu o seguinte erro.
> 
> 
> OBS: Usei o arquivo disponível para download em INSTALL.md
> Versão WebStorm 2019.2

Track the problem #9

**Comment by Brunowilliang** [comment]
Ok, tranks

**Comment by Mayconsgs** [comment]
Hey @Brunowilliang , this problem is similar to problem #8. And as @breno-felipe said, it is already being solved.

Soon the next version of the plugin will be available, and the problem will probably be solved.

**Comment by jpedroschmitz** [comment]
Just a quick note: when contributing to the project, refrain from using any other language than English 💜

**Comment by jpedroschmitz** [comment]
I think we can close this issue. What do you think, @Mayconsgs?

**Comment by Brunowilliang** [comment]
Got it, I'll test it again, I'll tell you

**Comment by Mayconsgs** [comment]
Yes, let's wrap up. I will generate a new version of the plugin and update the installation file.

Sorry for the delay, I had to pay extra attention to some college projects.

**Comment by breno-felipe** [comment]
With the problem reported and the correction made, I will close this problem

**Comment by Mayconsgs** [comment]
Hey @Brunowilliang, the [latest version](https://github.com/getomni/jetbrains/releases/latest) is now available. Just download the file Omni.Theme-x.x.x.zip, and follow the [Activating theme](https://github.com/getomni/jetbrains/blob/main/INSTALL.md#activating-theme) steps as usual.

I did everything I could to correct this problem. If it persists, I recommend that you update your development tool.
 
The installation file is already being updated to the new format.
