### ISSUE TITLE
Omni theme not supported in Webstorm version

### ISSUE THREAD

**Issue by lfoliveir4** [getomni/jetbrains#34]
**Description of bug**
new version of IDE does not support omni theme

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/32423942/128073129-b01f1359-10ac-4bec-b2f5-0e420ac83bdd.png)

**Environment:**
macOS Bug Sur

**Additional context**

**Comment by mayconsgs** [comment]
Hey @lfoliveir4 !
Thanks for report this issue.
I working to resolve this issue.

**Comment by lfoliveir4** [comment]
Hi! @mayconsgs, Thank you very much for the feedback! I'm waiting for the update, this theme is very good 😄😄😄😄!

**Comment by lfoliveir4** [comment]
@mayconsgs With your new PR already performs this fix? What guidance do you give to install the theme again?

**Comment by mayconsgs** [comment]
Yes, version 0.1.4 fixes this issue.
I tested the theme in new versions of the following IDEs:
* Android Studio
* Intellij
* PyCharm

And everything is working.

To install the new version, just follow the installation process again, but this time with the .zip from *0.1.4*.

I'm just waiting for #35  approval. As soon as the new version comes out, I'll be back here to notify you.
