### ISSUE TITLE
plugin dont work in dataspell DS-221.5080.210

### ISSUE THREAD

**Issue by ThiagoBussola** [getomni/jetbrains#74]
Estou tentado utilizar o tema no dataspell mas não deu muito certo.

![image](https://user-images.githubusercontent.com/37162902/167680758-80f18e42-9cee-4bc8-9a05-d93887c10b81.png)

**Comment by mauriciord** [comment]
@ThiagoBussola 
I believe this is fixed here

https://github.com/getomni/jetbrains/pull/77
