### ISSUE TITLE
Checked if the Omni plugin is compatible with IntelliJ 2019.1.4

### ISSUE THREAD

**Issue by breno-felipe** [getomni/jetbrains#8]
Following the guidelines for installing the Omni theme on JetBrains available at  [INSTALL.md](https://github.com/getomni/jetbrains/blob/main/INSTALL.md), I was unable to install the theme plugin on IntelliJ.

After following the guidelines of the  [INSTALL.md](https://github.com/getomni/jetbrains/blob/main/INSTALL.md) an error is returned, as shown in the image below.

![image](https://user-images.githubusercontent.com/50807243/112415612-db157680-8d02-11eb-9727-b7cab6583098.png)

`OBS: I used the file available for download at INSTALL.md`

`Version IntelliJ 2019.1.4`

Does the plugin only support the latest versions of JetBrains editors ?

**Comment by Mayconsgs** [comment]
Hey, @breno-felipe, thanks for reporting this issue.
The plugin is still in its early stages of development and it is very important that problems like these are reported.

I am already working to solve this problem.

Soon I will return with more news.

**Comment by breno-felipe** [comment]
Hey, @Mayconsgs,

Thank you for responding to my problem.

I look forward to the next updates

**Comment by Mayconsgs** [comment]
Hey @jpedroschmitz, compatibility changes made. Awaiting review by PR.

**Comment by jpedroschmitz** [comment]
I think we can close this issue. What do you think, @Mayconsgs?

**Comment by breno-felipe** [comment]
Hey @jpedroschmitz , @Mayconsgs 

Now, with the latest updates with the compatibility fix, you need to download the zip available at INSTALL.md ?

**Comment by jpedroschmitz** [comment]
I think @Mayconsgs will release a new version soon, with the fix!

**Comment by Mayconsgs** [comment]
@breno-felipe I am updating the installation file now. In the new version, some compatibility issues have been fixed. The new version will be available today.

**Comment by breno-felipe** [comment]
OK, I'm waiting for the new version to be available

**Comment by breno-felipe** [comment]
With the problem reported and the correction made, I will close this problem
